"""Dataset, data transforms and dataloader construction.

Originally extracted from cells 15-19 and 26-28 of vit3.ipynb (byte-identical in
unet_with_supervision_stacked.ipynb). It is now HAND-MAINTAINED rather than
regenerated by extract_model.py: the notebook's classes close over module-level
globals (NUM_LANDMARKS, model_image_size, ...), and those have been hoisted into
explicit constructor arguments, so this file deliberately no longer matches the
notebook's text.

All tunable values live in data_config.json:

    from custom_data_io import DataConfig, build_dataset, build_dataloaders

    cfg = DataConfig.load()                      # or DataConfig.load("other.json")
    train, val, test = build_dataloaders(build_dataset(cfg), cfg)

Numerics are unchanged from the notebook; only the plumbing differs.
"""

import json
import os
from dataclasses import asdict, dataclass, field, fields, is_dataclass
from typing import Tuple

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split
import torchvision.transforms as transforms
import torchvision.transforms.functional as TF
from PIL import Image

CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "data_config.json")


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class HeatmapConfig:
    """Gaussian target heatmaps.

    Only `max_sigma` is live. `min_sigma` and `sigma_ratio` feed the
    distance-adaptive sigma the notebook has commented out in coord_to_heatmap;
    they are kept so that experiment can be switched back on from config.
    """
    max_sigma: float = 5.0
    min_sigma: float = 1.0
    sigma_ratio: float = 0.05


@dataclass(frozen=True)
class AffineConfig:
    degrees: Tuple[float, float] = (-180.0, 180.0)
    translate: Tuple[float, float] = (0.0, 0.0)
    scale: Tuple[float, float] = (1.3, 1.5)
    shear: Tuple[float, float] = (-7.0, 7.0)


@dataclass(frozen=True)
class ColorMatrixConfig:
    max_spectral_norm: float = 1.5
    min_spectral_norm: float = 0.95
    # Std of the perturbation added to the identity colour matrix.
    jitter: float = 0.1


@dataclass(frozen=True)
class NoiseConfig:
    p: float = 0.7
    mean: float = 0.0
    std: float = 0.025


@dataclass(frozen=True)
class SplitConfig:
    train: float = 0.8
    val: float = 0.1
    seed: int = 42


@dataclass(frozen=True)
class DataConfig:
    image_size: int = 324
    model_image_size: int = 128
    num_landmarks: int = 5
    batch_size: int = 16
    # The notebook declared workers=2 but never passed it to DataLoader; 0 keeps
    # the behaviour it actually ran with.
    workers: int = 0

    # Which model to build; a key of model_registry.MODELS.
    model: str = "unet"
    rootdir: str = "/Users/ishwar/Downloads"
    output_dir: str = "model_output_090526_128x128_unet"

    # Optimizer settings. These are per-architecture: the U-Net was tuned at
    # 0.0005 / 0.5, the transformer at 0.0002 / 0.1.
    lr: float = 0.0005
    clip_max_norm: float = 0.5

    # Checkpoint to load for inference/examination, relative to output_dir.
    checkpoint: str = "info_model_060626_1000.pt"
    num_epochs: int = 1000

    csv_path: str = "plane_data/labeled_points_mega_grp.csv"
    images_dir: str = "outp"
    image_pattern: str = "frame_{frame}.png"

    heatmap: HeatmapConfig = field(default_factory=HeatmapConfig)
    affine: AffineConfig = field(default_factory=AffineConfig)
    color_matrix: ColorMatrixConfig = field(default_factory=ColorMatrixConfig)
    noise: NoiseConfig = field(default_factory=NoiseConfig)
    split: SplitConfig = field(default_factory=SplitConfig)

    @classmethod
    def from_dict(cls, d):
        """Build from a plain dict, recursing into the nested config sections.

        Unknown keys are an error rather than being ignored, so a typo in the
        JSON surfaces immediately instead of silently leaving a default in place.
        """
        return _from_dict(cls, d)

    @classmethod
    def load(cls, path=CONFIG_PATH):
        with open(path) as f:
            return cls.from_dict(json.load(f))

    def save(self, path=CONFIG_PATH):
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=2)
            f.write("\n")

    def replace(self, **kw):
        """A copy with overrides, e.g. cfg.replace(batch_size=8)."""
        return _from_dict(type(self), {**asdict(self), **kw})


def _from_dict(cls, d):
    known = {f.name: f for f in fields(cls)}
    unknown = set(d) - set(known)
    if unknown:
        raise ValueError(f"{cls.__name__}: unknown config keys {sorted(unknown)}")
    kw = {}
    for name, value in d.items():
        ftype = known[name].type
        if is_dataclass(ftype) and isinstance(value, dict):
            kw[name] = _from_dict(ftype, value)
        elif isinstance(value, list):
            kw[name] = tuple(value)
        else:
            kw[name] = value
    return cls(**kw)


# --------------------------------------------------------------------------- #
# Landmark / heatmap helpers
# --------------------------------------------------------------------------- #

def gen_coordinates(coord_array, num_landmarks):
    # make 7 coordinates from 5 coordinates
    coord_array_new = torch.zeros((num_landmarks, 2))
    coord_array_new[0] = coord_array[0]
    coord_array_new[1] = coord_array[1]
    coord_array_new[2] = (1/2)*((3/5)*coord_array[3] + (2/5)*coord_array[0]) + (1/2)*coord_array[1] # on left wing
    coord_array_new[3] = coord_array[2]
    coord_array_new[4] = (1/2)*((3/5)*coord_array[3] + (2/5)*coord_array[0]) + (1/2)*coord_array[2] # on right wing
    coord_array_new[5] = coord_array[3]
    coord_array_new[6] = coord_array[4]

    coord_array_new[7] = (3/4)*coord_array[0] + (1/4)*coord_array[3]
    coord_array_new[8] = (1/2)*coord_array[0] + (1/2)*coord_array[3]
    coord_array_new[9] = (1/4)*coord_array[0] + (3/4)*coord_array[3]

    return coord_array_new


def coord_to_heatmap(coord_array, image_shape, num_landmarks, heatmap, device):
    """Gaussian heatmap per landmark, each normalized to sum to 1.

    `heatmap` is a HeatmapConfig.
    """
    heatmaps = torch.zeros((num_landmarks, image_shape[1], image_shape[2]))

    for i in range(num_landmarks):
        mu_x, mu_y = coord_array[i][0], coord_array[i][1]   # center (x,y)
        # calculate average square root distance
        coord_diff = coord_array - torch.stack([coord_array[i],]*num_landmarks)
        mag = torch.linalg.vector_norm(coord_diff, 2, dim=1)
        mag_remove = torch.cat((mag[:i], mag[i+1:]))
        s = torch.pow(torch.mean(torch.pow(mag_remove + 1e-5, -1)), -1)
        sigma = heatmap.max_sigma
        # distance-adaptive alternative, disabled in the notebook:
        # sigma = min(heatmap.sigma_ratio * s + heatmap.min_sigma, heatmap.max_sigma)

        ys = torch.arange(image_shape[1], device=device, dtype=torch.float32)
        xs = torch.arange(image_shape[2], device=device, dtype=torch.float32)
        yy, xx = torch.meshgrid(ys, xs, indexing='ij')          # HxW each

        img = torch.exp(-0.5 * ((xx - mu_x)**2 + (yy - mu_y)**2) / (sigma**2))
        heatmaps[i] = (img / (img.sum() + 1e-5))
    return heatmaps


# --------------------------------------------------------------------------- #
# Transforms
# --------------------------------------------------------------------------- #

class RandomAdditiveNoise:
    def __init__(self, p=0.5, mean=0.0, std=0.05):
        self.p = p
        self.mean = mean
        self.std = std

    @classmethod
    def from_config(cls, noise):
        return cls(p=noise.p, mean=noise.mean, std=noise.std)

    def __call__(self, x):
        # x: tensor in [0,1], shape (C, H, W)
        if torch.rand(1).item() < self.p:
            noise = torch.randn_like(x) * self.std + self.mean
            x = x + noise
            x = torch.clamp(x, 0.0, 1.0)
        return x


class RandomColorMatrix:
    """
    Applies x -> A x where A is 3x3 with:
      - rank in {1, 2, 3} (each w.p. 1/3)
      - spectral norm <= max_spectral_norm
    """
    def __init__(self, max_spectral_norm=1.5, min_spectral_norm=0.75, jitter=0.1):
        self.max_spectral_norm = max_spectral_norm
        self.min_spectral_norm = min_spectral_norm
        self.jitter = jitter

    @classmethod
    def from_config(cls, color_matrix):
        return cls(max_spectral_norm=color_matrix.max_spectral_norm,
                   min_spectral_norm=color_matrix.min_spectral_norm,
                   jitter=color_matrix.jitter)

    def _random_orthonormal(self):
        """Generate a random 3x3 orthonormal matrix via QR."""
        M = torch.randn(3, 3)
        Q, _ = torch.linalg.qr(M)  # Q is orthonormal
        return Q

    def __call__(self, x):
        # x: tensor in [0,1], shape (3, H, W)
        c, h, w = x.shape
        assert c == 3, "RandomColorMatrix expects a 3-channel RGB tensor."

        # The full rank-sampling / SVD construction is disabled in the notebook;
        # what runs is the identity plus a small perturbation.
        A = torch.eye(c)
        A += torch.randn_like(A)*self.jitter

        # Apply A to each pixel: x_flat is 3 x (H*W)
        x_flat = x.view(3, -1)
        x_transformed = A @ x_flat
        x_out = x_transformed.view(3, h, w)

        # Clamp back to [0,1]
        x_out = torch.clamp(torch.abs(x_out), 0.0, 1.0)
        return x_out


class ComposeJoint:
    def __init__(self, transforms):
        self.transforms = transforms

    def __call__(self, img, pts):
        for t in self.transforms:
            img, pts = t(img, pts)
        return img, pts


class RandomAffineWithPoints:
    """
    Same params as torchvision.transforms.RandomAffine,
    but applied to both image and (N,2) coords.
    """
    def __init__(self, degrees, translate=None, scale=None, shear=None):
        self.degrees = degrees
        self.translate = translate
        self.scale = scale
        self.shear = shear

    @classmethod
    def from_config(cls, affine):
        return cls(degrees=affine.degrees, translate=affine.translate,
                   scale=affine.scale, shear=affine.shear)

    def __call__(self, img, pts):
        # img.size is (W, H)
        w, h = img.size()[1:]

        # Sample random params exactly like RandomAffine
        angle, translations, scale, shear = transforms.RandomAffine.get_params(
            self.degrees, self.translate, self.scale, self.shear, (w, h)
        )
        corner_pixel = (img[0, -1, -1].item(), img[1, -1, -1].item(), img[2, -1, -1].item())
        # --- 1) Transform the image ---
        img = TF.affine(
            img,
            angle=angle,
            translate=translations,
            scale=scale,
            shear=shear,
            interpolation = transforms.InterpolationMode.BILINEAR,
            fill=corner_pixel
        )

        center = [w * 0.5, h * 0.5]
        inv_coeffs = TF._get_inverse_affine_matrix(
            center=center,
            angle=angle,
            translate=translations,
            scale=scale,
            shear=shear
        )
        # inv_coeffs = [a, b, c, d, e, f] giving:
        # x_in  = a * x_out + b * y_out + c
        # y_in  = d * x_out + e * y_out + f
        a, b, c, d, e, f = inv_coeffs

        M_inv = torch.tensor(
            [[a, b],
             [d, e]],
            dtype=torch.float32,
            device=pts.device,
        )

        M = torch.inverse(M_inv)  # 2x2

        translation = torch.tensor([[c, f]]).repeat(pts.size()[0], 1)
        pts_tr = pts - translation
        pts_out = (M @ pts_tr.T).T

        return img, pts_out


def build_transforms(config):
    """The notebook's three-stage pipeline, built from config.

    Returns (transform, geo_transform, post_geo_transform).
    """
    transform = transforms.Compose([
        transforms.Resize(config.image_size),
        transforms.ToTensor(),
    ])
    geo_transform = ComposeJoint([
        RandomAffineWithPoints.from_config(config.affine),
    ])
    post_geo_transform = transforms.Compose([
        RandomColorMatrix.from_config(config.color_matrix),
        RandomAdditiveNoise.from_config(config.noise),
        transforms.Resize(config.model_image_size),
    ])
    return transform, geo_transform, post_geo_transform


# --------------------------------------------------------------------------- #
# Dataset
# --------------------------------------------------------------------------- #

class FramesFromCSV(Dataset):
    def __init__(self, config, transform=None, geo_transform=None,
                 post_geo_transform=None):
        """
        Args:
            config: DataConfig supplying csv_path, images_dir, image_pattern,
                image_size, model_image_size, num_landmarks and heatmap settings
            transform: optional torchvision transform applied to the PIL image
            geo_transform: optional joint (image, points) transform
            post_geo_transform: optional transform applied after geo_transform
        """
        self.config = config
        self.images_dir = config.images_dir
        self.image_pattern = config.image_pattern
        self.transform = transform
        self.geo_transform = geo_transform
        self.post_geo_transform = post_geo_transform

        # Load CSV into numpy array, skipping header
        self.data = np.loadtxt(config.csv_path, delimiter=",", skiprows=1)
        # Ensure it's 2D even if only one row
        if self.data.ndim == 1:
            self.data = np.expand_dims(self.data, axis=0)

        self.frame_numbers = self.data[:, 0].astype(int)
        self.points = self.data[:, 1:]

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        cfg = self.config
        frame_num = self.frame_numbers[idx]
        coords = self.points[idx]

        # Load image
        img_path = os.path.join(self.images_dir, self.image_pattern.format(frame=frame_num))
        image = Image.open(img_path).convert("RGB")

        # Reshape coords into Nx2 array (x, y)
        coords = coords.reshape(-1, 2)
        coords = torch.tensor(coords, dtype=torch.float32)

        if self.transform:
            image = self.transform(image)
        if self.geo_transform:
            image, coords = self.geo_transform(image, coords)
        if self.post_geo_transform:
            image = self.post_geo_transform(image)

        # augmented_coords = gen_coordinates(coords, cfg.num_landmarks)
        augmented_coords = coords * cfg.model_image_size / cfg.image_size
        normalized_image = image*2 - 1

        return {
            "image": normalized_image,
            "points": augmented_coords,
            "heatmaps": coord_to_heatmap(augmented_coords, image.shape,
                                         cfg.num_landmarks, cfg.heatmap, "cpu"),
            "frame": frame_num
        }


# --------------------------------------------------------------------------- #
# Construction
# --------------------------------------------------------------------------- #

def build_dataset(config=None):
    """The dataset the notebook builds, with every knob taken from config."""
    config = config or DataConfig.load()
    transform, geo_transform, post_geo_transform = build_transforms(config)
    return FramesFromCSV(config, transform=transform, geo_transform=geo_transform,
                         post_geo_transform=post_geo_transform)


def build_dataloaders(dataset, config=None, verbose=False):
    """Split `dataset` and wrap each part in a DataLoader.

    The split is seeded from config, so it reproduces the notebook's exactly.
    """
    config = config or DataConfig.load()
    split = config.split

    total_size = len(dataset)
    train_size = int(total_size * split.train)
    val_size = int(total_size * split.val)
    test_size = total_size - train_size - val_size  # Ensure all samples are used

    seed = torch.Generator().manual_seed(split.seed)
    train_dataset, val_dataset, test_dataset = random_split(
        dataset, [train_size, val_size, test_size], generator=seed)

    if verbose:
        print(f"Train size: {len(train_dataset)}")
        print(f"Validation size: {len(val_dataset)}")
        print(f"Test size: {len(test_dataset)}")

    train_loader = DataLoader(train_dataset, batch_size=config.batch_size,
                              shuffle=True, num_workers=config.workers)
    val_loader = DataLoader(val_dataset, batch_size=config.batch_size,
                            shuffle=False, num_workers=config.workers)
    test_loader = DataLoader(test_dataset, batch_size=config.batch_size,
                             shuffle=False, num_workers=config.workers)
    return train_loader, val_loader, test_loader
