"""U-Net / stacked-hourglass landmark model.

AUTOGENERATED by extract_model.py from unet_with_supervision_stacked.ipynb -- do not edit by hand.
Regenerate with:  python3 extract_model.py unet

Public API: StackedHourglass
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

# --- from notebook cell 2 ---
class SameSizeConv(nn.Module):
    def __init__(self, inchannels, outchannels, p_dropout, num_layers=2):
        super(SameSizeConv, self).__init__()
        self.p_dropout = p_dropout
        
        self.kernelSize = 5
        convs = []

        for _ in range(num_layers):
            convs.append(nn.Conv2d(inchannels, inchannels, self.kernelSize, stride=1, \
                    padding=(self.kernelSize-1)//2, bias=False) )
            convs.append(nn.Conv2d(inchannels, inchannels, self.kernelSize+2, stride=1, \
                    dilation=2, padding=(self.kernelSize+2-1), bias=False) )
            convs.append(nn.BatchNorm2d(inchannels))
            convs.append(nn.LeakyReLU())
            convs.append(nn.Dropout(p=self.p_dropout))

        convs.append(nn.Conv2d(inchannels, inchannels, 1, stride=1, \
                            padding=0, bias=False) )
        convs.append(nn.BatchNorm2d(inchannels))
        convs.append(nn.LeakyReLU())
        convs.append(nn.Dropout(p=self.p_dropout))

        convs.append(nn.Conv2d(inchannels, outchannels, 1, stride=1, \
                            padding=0, bias=False) )
        convs.append(nn.BatchNorm2d(outchannels))
        convs.append(nn.LeakyReLU())
        convs.append(nn.Dropout(p=self.p_dropout))

        self.res_conv = nn.Conv2d(inchannels, outchannels, 1, stride=1, padding=0, bias=False)
        
        self.conv_layers = nn.Sequential(*convs)
    
    def forward(self, x):
        return (self.conv_layers(x) + self.res_conv(x))


# --- from notebook cell 3 ---
class Up(nn.Module):
    log_stats = True  # aggregate gradient/value stats at this level, don't descend further

    def __init__(self, in_channels, out_channels, up):
        super(Up, self).__init__()

        if up == None:
            self.up = nn.ConvTranspose2d(in_channels, out_channels, 4, 2, 1, bias=False)
        else:
            self.up = up
        self.res_up = nn.ConvTranspose2d(in_channels, out_channels, 1, stride=1, padding=0, bias=False)
        self.scale_up = nn.Upsample(scale_factor=2, mode='nearest')

        self.kernelSize = 5
        self.batch_norm = nn.BatchNorm2d(out_channels)
        self.activation = nn.LeakyReLU()
        self.conv_layers = SameSizeConv(out_channels*2, out_channels, 0)

    def forward(self, x1, x2):
        x = self.activation(self.batch_norm(self.up(x1))) + self.scale_up(self.res_up(x1))
        x = torch.cat([x, x2], dim=1)
        x = self.conv_layers(x)
        return x


# --- from notebook cell 4 ---
#not used
class Up2(nn.Module):
    log_stats = True

    def __init__(self, in_channels, out_channels, up):
        super(Up2, self).__init__()

        if up == None:
            self.up = nn.ConvTranspose2d(in_channels, out_channels, 4, 2, 1, bias=False)
        else:
            self.up = up
        self.res_up = nn.ConvTranspose2d(in_channels, out_channels, 1, stride=1, padding=0, bias=False)
        self.scale_up = nn.Upsample(scale_factor=2, mode='nearest')
        
        self.kernelSize = 5
        self.batch_norm = nn.BatchNorm2d(out_channels)
        self.activation = nn.LeakyReLU()
        self.conv_layers = SameSizeConv(out_channels, out_channels, 0)

    def forward(self, x):
        x = self.activation(self.batch_norm(self.up(x))) + self.scale_up(self.res_up(x))
        x = self.conv_layers(x)
        return x


# --- from notebook cell 5 ---
class Down(nn.Module):
    log_stats = True

    def __init__(self, in_channels, out_channels, down):
        super(Down, self).__init__()

        self.kernelSize = 5
        if down == None:
            self.down = nn.Conv2d(in_channels, out_channels, 4, 2, 1, bias=False)
        else:
            self.down = down
        self.res_down = nn.Conv2d(in_channels, out_channels, 1, stride=1, padding=0, bias=False)
        self.scale_down = nn.MaxPool2d((2, 2), stride=(2, 2))
        
        self.batch_norm = nn.BatchNorm2d(out_channels)
        self.activation = nn.LeakyReLU()
        self.conv_layers = SameSizeConv(out_channels, out_channels, 0)

    def forward(self, x):
        x = self.activation(self.batch_norm(self.down(x))) + self.scale_down(self.res_down(x))
        x = self.conv_layers(x)
        return x


# --- from notebook cell 6 ---
class UNet(nn.Module):
    def __init__(self, in_channels, out_channels, supervised_channels, num_skip=6):
        super(UNet, self).__init__()
        
        self.modules = []
        self.kernelSize = 5 # must be odd
        self.p_dropout = 0
        self.num_skip = num_skip
        self.supervised_channels = supervised_channels

        channels = (in_channels, 16)
        self.init_conv = SameSizeConv(channels[0], channels[1], self.p_dropout)
        self.convs0 = SameSizeConv(channels[1], self.supervised_channels + channels[1], self.p_dropout, num_layers=1)
        self.convs0a = SameSizeConv(self.supervised_channels + channels[1], channels[1], self.p_dropout, num_layers=1)
        
        # downsizing
        channels = (16, 16)
        self.downsize1 = Down(channels[0], channels[1], None)
        self.ups1 = nn.Upsample(scale_factor=2, mode='nearest')
        self.convs1 = SameSizeConv(channels[1], self.supervised_channels + channels[1], self.p_dropout, num_layers=1)
        self.convs1a = SameSizeConv(self.supervised_channels + channels[1], channels[1], self.p_dropout, num_layers=1)

        channels = (16, 32)
        self.downsize2 = Down(channels[0], channels[1], None)
        self.ups2 = nn.Upsample(scale_factor=4, mode='nearest')
        self.convs2 = SameSizeConv(channels[1], self.supervised_channels + channels[1], self.p_dropout, num_layers=1)
        self.convs2a = SameSizeConv(self.supervised_channels + channels[1], channels[1], self.p_dropout, num_layers=1)

        channels = (32, 64)
        self.downsize3 = Down(channels[0], channels[1], None)
        self.ups3 = nn.Upsample(scale_factor=8, mode='nearest')
        self.convs3 = SameSizeConv(channels[1], self.supervised_channels + channels[1], self.p_dropout, num_layers=1)
        self.convs3a = SameSizeConv(self.supervised_channels + channels[1], channels[1], self.p_dropout, num_layers=1)

        channels = (64, 128)
        self.downsize4 = Down(channels[0], channels[1], None)

        self.lowest_convs = SameSizeConv(channels[1], channels[1], self.p_dropout, num_layers=2)

        num_skip_temp = self.num_skip

        channels = (128, 64)
        self.upsize4 =  Up(channels[0], channels[1], None) if (num_skip_temp > 0) else Up2(channels[0], channels[1], None)
        num_skip_temp -= 1

        channels = (64, 32)
        self.upsize3 =  Up(channels[0], channels[1], None) if (num_skip_temp > 0) else Up2(channels[0], channels[1], None)
        num_skip_temp -= 1

        channels = (32, 16)
        self.upsize2 =  Up(channels[0], channels[1], None) if (num_skip_temp > 0) else Up2(channels[0], channels[1], None)
        num_skip_temp -= 1

        channels = (16, 16)
        self.upsize1 =  Up(channels[0], channels[1], None) if (num_skip_temp > 0) else Up2(channels[0], channels[1], None)
        num_skip_temp -= 1

        self.final_conv = SameSizeConv(channels[1], out_channels, self.p_dropout)

        # Stats groups (see log_module_stats). Down/Up/Up2 carry log_stats as a class
        # attribute; SameSizeConv can't, since it is also the block *inside* those. Tag
        # only the ones UNet owns directly, so every parameter falls in exactly one group.
        for child in self.children():
            if isinstance(child, SameSizeConv):
                child.log_stats = True


    def forward(self, input):
        x0 = self.init_conv(input)

        x1 = self.downsize1(x0)
        x1 = F.dropout(x1, p=self.p_dropout)

        x2 = self.downsize2(x1)
        x2 = F.dropout(x2, p=self.p_dropout)

        x3 = self.downsize3(x2)
        x3 = F.dropout(x3, p=self.p_dropout)

        x4 = self.downsize4(x3)
        x4 = F.dropout(x4, p=self.p_dropout)

        f5 = self.lowest_convs(x4)


        num_skip_temp = self.num_skip
        if (num_skip_temp > 0):
            y3 = self.convs3(x3); num_skip_temp -= 1
        if (num_skip_temp > 0):
            y2 = self.convs2(x2); num_skip_temp -= 1
        if (num_skip_temp > 0):
            y1 = self.convs1(x1); num_skip_temp -= 1
        if (num_skip_temp > 0):
            y0 = self.convs0(x0); num_skip_temp -= 1

        #inter3 = self.ups3(y3[:, :self.supervised_channels, :, :])
        #inter2 = self.ups2(y2[:, :self.supervised_channels, :, :])
        #inter1 = self.ups1(y1[:, :self.supervised_channels, :, :])
        #inter0 = y0[:, :self.supervised_channels, :, :]

        num_skip_temp = self.num_skip

        x = self.upsize4(f5, self.convs3a(y3)) if (num_skip_temp > 0) else self.upsize4(f5)
        x = F.dropout(x, p=self.p_dropout)
        num_skip_temp -= 1

        x = self.upsize3(x, self.convs2a(y2)) if (num_skip_temp > 0) else self.upsize4(x)
        x = F.dropout(x, p=self.p_dropout)
        num_skip_temp -= 1

        x = self.upsize2(x, self.convs1a(y1)) if (num_skip_temp > 0) else self.upsize4(x)
        x = F.dropout(x, p=self.p_dropout)
        num_skip_temp -= 1

        x = self.upsize1(x, self.convs0a(y0)) if (num_skip_temp > 0) else self.upsize4(x)
        x = F.dropout(x, p=self.p_dropout)
        num_skip_temp -= 1

        x = self.final_conv(x)

        return [x]#, inter0, inter1, inter2, inter3


# --- from notebook cell 7 ---
class StackedHourglass(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(StackedHourglass, self).__init__()
        self.inchannels = in_channels
        self.outchannels = out_channels
        self.criterion = nn.MSELoss()   # default for error(); override per call if needed
        self.unet1 = UNet(in_channels, out_channels, 0)
        ##self.unet1 = UNet(in_channels, 8+out_channels, out_channels)
        ##self.unet2 = UNet(8+out_channels+in_channels, 8+out_channels, out_channels)
        ##self.unet3 = UNet(8+out_channels+in_channels, out_channels, out_channels)
        #self.unet3 = UNet(8, 8)
        #self.unet4 = UNet(8, out_channels)
    def forward(self, input):
        unet1_ans = self.unet1(input)
        #x = torch.cat([input, unet1_ans[0]], dim=1)
        #unet2_ans = self.unet2(x)
        #x = torch.cat([input, unet2_ans[0]], dim=1)
        #unet3_ans = self.unet3(x)

        endpt_logits = [unet1_ans[0][:, :self.outchannels, :, :]]#, unet2_ans[0][:, :self.outchannels, :, :], unet3_ans[0][:, :self.outchannels, :, :]]
        interior_logits = unet1_ans[1:] # + unet2_ans[1:] + unet3_ans[1:]

        x = unet1_ans[0]
        b = x.shape[0]
        c = self.outchannels
        ##interior = [ F.softmax(heatmap.view(b, c, model_image_size*model_image_size), dim=2).view((b,c,model_image_size,model_image_size))
            ##for heatmap in interior_logits ]
        #x = self.unet2(x)
        #x = self.unet3(x)
        #x = self.unet4(x)
        #x = F.sigmoid(x)
        return endpt_logits##, interior

    def forward_display(self, input, tau=1.0):
        """Like forward(), but returns heatmaps ready to plot rather than to train on.

        Runs in .eval() mode under no_grad, restoring the previous mode afterwards,
        and returns (stage_logits, stage_probs) as lists of (B, C, H, W) tensors
        detached on the CPU. Display code can then loop over the lists without
        knowing how many stages this model has, whether they need a softmax, or
        which device they came off.

        tau -- temperature applied to the logits before the softmax:
               probs = softmax(logits / tau). Below 1.0 sharpens the distribution,
               which matters when a soft-argmax reads coordinates off it: a flat
               heatmap pulls the estimate toward the image centre. 1.0 leaves the
               logits alone. The returned logits are always the raw ones.
        """
        was_training = self.training
        self.eval()
        with torch.no_grad():
            stage_logits = self(input)
            stage_probs = self.heatmap_softmax([y / tau for y in stage_logits])
        if was_training:
            self.train()
        return [y.cpu() for y in stage_logits], [y.cpu() for y in stage_probs]

    def heatmap_softmax(self, heatmap_list):
        """Spatial softmax of each stage's logits: normalize over H*W per channel.

        Shapes are taken from the tensors, so no model_image_size global is needed and
        a batch of any size (including 1, for visualization) works unchanged.
        """
        probs = []
        for heatmap in heatmap_list:
            b, c, h, w = heatmap.shape
            probs.append(F.softmax(heatmap.reshape(b, c, h * w), dim=2).reshape(b, c, h, w))
        return probs

    def error(self, heatmap_logits, target, criterion=None, stage=0,
              batch_size=None, loss_scale=1.0):
        """Spatial-softmax the stage logits, pick one stage, and score it against target.

        heatmap_logits -- what forward() returned (list, one entry per stage).
        stage          -- which entry to score; 0 is the only one while unet2/unet3
                          are commented out, but keeping it explicit means re-enabling
                          them is a loop over stages here rather than a rewrite.
        batch_size     -- if given, scale by (actual batch / batch_size) so a short
                          final batch contributes proportionally rather than equally.
        loss_scale     -- constant factor to lift the loss out of the range the
                          softmax leaves it in (probabilities over h*w cells are ~1e-5,
                          so MSE against them is ~1e-10 before scaling).

        Returns the loss alone. Callers that need the probabilities themselves --
        display code -- get them from forward_display().
        """
        predicted = self.heatmap_softmax(heatmap_logits)[stage]
        err = (criterion if criterion is not None else self.criterion)(predicted, target)
        if batch_size:
            err = err * predicted.shape[0] / batch_size
        return err * loss_scale

        ###errs_endpts = []
        ###for j in range(len(heatmap_predicted[0])):
        ###    errs_endpts.append(criterion(heatmap_predicted[0][j], output))
        ###    print(f"Error for intermediate heatmap {j}: {errs_endpts[j].item()}")
        ###losses.append((epoch, i, iters, {f"Stage {j} error endpt": errs_endpts[j].item() for j in range(len(heatmap_predicted[0]))} ) )
        ###err_endpts_sum = (sum(errs_endpts)/len(errs_endpts)) * b / batch_size

        # errs_interior = []
        # for j in range(len(heatmap_predicted[1])):
        #     errs_interior.append(criterion(heatmap_predicted[1][j], output))
        #     print(f"Error for intermediate heatmap {j}: {errs_interior[j].item()}")

        # losses.append((epoch, i, iters, {f"Stage {j} error interior": errs_interior[j].item() for j in range(len(heatmap_predicted[1]))} ) )
        # err_interior_sum = (sum(errs_interior)/len(errs_interior)) * b / batch_size

