"""Vision-transformer landmark model.

AUTOGENERATED by extract_model.py from vit3.ipynb -- do not edit by hand.
Regenerate with:  python3 extract_model.py vit

Public API: VisionTransformer, weights_init, SameSizeConv, gen_ape, VisionAttention
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

# --- from notebook cell 6 ---
class SameSizeConv(nn.Module):
    def __init__(self, inchannels, outchannels, p_dropout, num_layers=2):
        super(SameSizeConv, self).__init__()
        self.p_dropout = p_dropout
        
        self.kernelSize = 3
        convs = []

        for _ in range(num_layers):
            convs.append(nn.Conv2d(inchannels, inchannels, self.kernelSize, stride=1, \
                    padding=(self.kernelSize-1)//2, bias=False) )
            convs.append(nn.Conv2d(inchannels, inchannels, self.kernelSize+2, stride=1, \
                    dilation=2, padding=(self.kernelSize+2-1), bias=False) )
            convs.append(nn.BatchNorm2d(inchannels))
            convs.append(nn.LeakyReLU())
            convs.append(nn.Dropout(p=self.p_dropout))

        mlp = []
        mlp.append(nn.Conv2d(inchannels, inchannels, 1, stride=1, \
                            padding=0, bias=False) )
        mlp.append(nn.BatchNorm2d(inchannels))
        mlp.append(nn.LeakyReLU())
        mlp.append(nn.Dropout(p=self.p_dropout))

        mlp.append(nn.Conv2d(inchannels, outchannels, 1, stride=1, \
                            padding=0, bias=False) )
        mlp.append(nn.BatchNorm2d(outchannels))
        mlp.append(nn.LeakyReLU())
        mlp.append(nn.Dropout(p=self.p_dropout))

        self.res_conv = nn.Conv2d(inchannels, inchannels, 1, stride=1, padding=0, bias=False)
        self.res_mlp = nn.Conv2d(inchannels, outchannels, 1, stride=1, padding=0, bias=False)
        
        self.conv_layers = nn.Sequential(*convs)
        self.mlp_layers = nn.Sequential(*mlp)
    
    def forward(self, x):
        x2 = self.conv_layers(x) + self.res_conv(x)
        return self.mlp_layers(x2) + self.res_mlp(x2)


# --- from notebook cell 8 ---
# Absolute Position Encoding (32 channels)
def gen_ape(num_channels, img_size):
    num_channels = torch.tensor(num_channels) # must be a multiple of 4 to have sin & cos for both x and y axes
    img_size = torch.tensor(img_size)
    NQ = torch.tensor(4)

    varying_dim = torch.linspace(0, img_size-1, steps=img_size)
    static_dim = torch.linspace(0, 0, steps=img_size)
    wavelength_dim = torch.linspace(torch.log(NQ)/torch.log(img_size), 1, steps=num_channels//4)
    wavelength_dim = torch.pow(img_size, wavelength_dim)

    # make first dim position encoding
    grid_tuple = torch.meshgrid(wavelength_dim, varying_dim, static_dim, indexing='ij')
    dim1_ape = torch.concat(\
                        (torch.sin((1 /  grid_tuple[0]) * grid_tuple[1] * 2*torch.pi), 
                            torch.cos((1 /  grid_tuple[0]) * grid_tuple[1] * 2*torch.pi)) )
    # make second dim position encoding
    grid_tuple = torch.meshgrid(wavelength_dim, static_dim, varying_dim, indexing='ij')
    dim2_ape = torch.concat(\
                        (torch.sin((1 /  grid_tuple[0]) * grid_tuple[2] * 2*torch.pi), 
                            torch.cos((1 /  grid_tuple[0]) * grid_tuple[2] * 2*torch.pi)) )
    ape = torch.concat((dim1_ape, dim2_ape))

    #ape_seq = torch.permute(torch.flatten(ape, start_dim=1, end_dim=2), (1, 0))

    return ape


# --- from notebook cell 10 ---
class VisionAttention(nn.Module):
    log_stats = True  # aggregate gradient/value stats at this level, don't descend further

    def __init__(self, image_size, inchannels, qkchannels, vchannels):
        super(VisionAttention, self).__init__()

        # need to know how to customize initialization broadly
        self.image_size = image_size
        self.qkchannels = qkchannels
        self.qkscalar = torch.sqrt(torch.tensor(self.qkchannels))
        
        self.vchannels = vchannels
        self.queryMatrix = nn.Parameter(torch.empty(inchannels, qkchannels), requires_grad=True)
        self.keyMatrix = nn.Parameter(torch.empty(inchannels, qkchannels), requires_grad=True)
        self.valueMatrix = nn.Parameter(torch.empty(inchannels, vchannels), requires_grad=True)

        self.ape = torch.permute(torch.flatten(gen_ape(qkchannels, self.image_size), start_dim=1, end_dim=2), (1, 0))

        self.res = ResidualNorm(inchannels, vchannels)

        self.mlp = MLP(vchannels, vchannels)
    
    def forward(self, x): # x should be of dimension (batch, channels, imx, imy) ->(batch, length of sequence, dimension of embedding)
        x_seq = torch.flatten(torch.permute(x, (0, 2, 3, 1)), start_dim=1, end_dim=2)
        queries = torch.matmul(x_seq+self.ape, self.queryMatrix)
        keys = torch.matmul(x_seq+self.ape, self.keyMatrix)
        values = torch.matmul(x_seq, self.valueMatrix)
        cosine_sim = torch.matmul(queries, torch.permute(keys, (0, 2, 1))) / self.qkscalar
        attention = F.softmax(cosine_sim, dim=2) # dimension 2 contains all dot products for one query and all keys
        values = torch.matmul(attention, values)
        values_image = torch.unflatten(torch.permute(values, (0, 2, 1)), dim=2, sizes=(self.image_size, self.image_size))

        out_image = self.res(x, values_image)

        mlp_image = self.mlp(out_image)

        return mlp_image


# --- from notebook cell 2 ---
class _ContiguousGrad(torch.autograd.Function):
    """Identity in the forward pass; makes the gradient contiguous on the way back.

    Works around a torch 2.1.0 MPS bug: nn.Conv2d's backward produces garbage when its
    grad_output is non-contiguous (verified: cosine similarity vs the CPU result ~0.007
    for grad_input and ~0.003 for grad_weight -- i.e. noise, not error).

    ChannelLayerNorm ends in a permute, and that permute's backward hands exactly such a
    non-contiguous tensor to whatever conv feeds it. In VisionTransformer every
    MultiHeadVisionAttention routes `combine` and `resnorm.res_conv` into a
    ChannelLayerNorm, so on MPS every parameter upstream of the last one -- all three
    attention blocks, norm1, resizechannels and learnable_ape -- received noise instead
    of a gradient, and the model never learned. The decoder, which sits downstream of
    every ChannelLayerNorm, trained correctly, which is why the symptom was a loss
    pinned at the uniform-heatmap floor rather than a divergence.

    Applying this to the *input* is what matters: it is the gradient LEAVING this module
    toward the conv that has to be contiguous. Making the forward output contiguous does
    nothing, since that never touches the backward tensor.
    """
    @staticmethod
    def forward(ctx, x):
        return x

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output.contiguous()


class ChannelLayerNorm(nn.LayerNorm):
    def __init__(self, num_channels, channel_dim, num_dims):
        super(ChannelLayerNorm, self).__init__(num_channels)
        # build ro
        ro = []
        for i in range(num_dims-1):
            if i >= channel_dim:
                ro.append(i+1)
            else:
                ro.append(i)
        ro.append(channel_dim)

        ro_inv = []
        for i in range(num_dims):
            if i == channel_dim:
                ro_inv.append(num_dims-1)
            elif i > channel_dim:
                ro_inv.append(i-1)
            else:
                ro_inv.append(i)
        
        self.ro = tuple(ro)
        self.ro_inv = tuple(ro_inv)

        print(self.ro)
        print(self.ro_inv)

    def forward(self, x):
        # See _ContiguousGrad: without this the conv feeding this module gets a
        # non-contiguous grad_output and silently returns noise on MPS.
        x = _ContiguousGrad.apply(x)
        x_perm = torch.permute(x, self.ro)
        layernorm_x = super().forward(x_perm)
        return torch.permute(layernorm_x, self.ro_inv)


# --- from notebook cell 3 ---
class ResidualNorm(nn.Module):
    def __init__(self, inchannels, outchannels):
        super(ResidualNorm, self).__init__()

        self.res_conv = nn.Conv2d(inchannels, outchannels, 1, stride=1, padding=0, bias=False)
        self.layer_norm = ChannelLayerNorm(outchannels, 1, 4)# nn.LayerNorm(outchannels)

    def forward(self, x_orig, x):
        res_image = x + self.res_conv(x_orig)
        # TODO: put layer norm before residual (+x)
        out_image = self.layer_norm(res_image) #torch.permute(self.layer_norm(torch.permute(res_image, (0, 2, 3, 1))), (0, 3, 1, 2))
        return out_image


# --- from notebook cell 4 ---
class Residual(nn.Module):
    def __init__(self, inchannels, outchannels):
        super(Residual, self).__init__()

        self.res_conv = nn.Conv2d(inchannels, outchannels, 1, stride=1, padding=0, bias=False)

    def forward(self, x_orig, x):
        res_image = x + self.res_conv(x_orig)
        return res_image


# --- from notebook cell 5 ---
class MLP(nn.Module):
    def __init__(self, inchannels, outchannels, num_layers=3):
        super(MLP, self).__init__()

        conv_layers = []
        for i in range(num_layers):
            endchannels = outchannels if (i == num_layers-1) else inchannels
            conv_layers.append(nn.Conv2d(inchannels, endchannels, 1, stride=1, padding=0, bias=False))
            conv_layers.append(nn.BatchNorm2d(endchannels))
            conv_layers.append(nn.LeakyReLU())

        self.conv_layers = nn.Sequential(*conv_layers)
        self.res = Residual(inchannels, outchannels)

    def forward(self, x):
        return self.res(x, self.conv_layers(x))


# --- from notebook cell 7 ---
class PatchConv(nn.Module):
    def __init__(self, in_channels, patch_size):
        super(PatchConv, self).__init__()
        with torch.no_grad():
            patch_arr = torch.reshape(torch.eye(patch_size**2), (patch_size**2, patch_size, patch_size))
            patch_weights = torch.zeros((in_channels * patch_size**2, in_channels, patch_size, patch_size))
            for i in range(in_channels * patch_size**2):
                patch_weights[i, i % in_channels] = patch_arr[i // in_channels]
            patch_weights.to(dtype=torch.float32)
            self.patch_filter = nn.Conv2d(in_channels, in_channels * patch_size**2, patch_size, stride=patch_size, padding=0, bias=False)
            self.patch_filter.weight = nn.Parameter(patch_weights)
        #self.patch_filter.weight.requires_grad = False
        # Freeze all parameters in the layer
        for param in self.patch_filter.parameters():
            param.requires_grad = False
    
    def forward(self, x):
        return self.patch_filter(x)


# --- from notebook cell 9 ---
def gen_learnable_ape(num_channels, img_size):
    x = torch.randn(num_channels, img_size, img_size)
    print(f"Learnable ape shape: {x.shape}")
    x_param = nn.Parameter(x, requires_grad=True)
    return x_param


# --- from notebook cell 11 ---
class MultiHeadVisionAttention(nn.Module):
    log_stats = True

    def __init__(self, image_size, inchannels, qkchannels, vchannels, numheads, given_ape=None):
        super(MultiHeadVisionAttention, self).__init__()

        # need to know how to customize initialization broadly
        self.image_size = image_size
        self.qkchannels = qkchannels
        self.qkscalar = torch.tensor(self.qkchannels)
        self.numheads = numheads

        self.initnorm = nn.LayerNorm(inchannels)
        
        self.vchannels = vchannels
        self.queryMatrix = nn.Parameter(torch.empty(numheads, inchannels, qkchannels), requires_grad=True)
        self.queryNorm = nn.LayerNorm(qkchannels)
        #self.register_parameter(name='queryMatrix', param=nn.Parameter(torch.empty(numheads, inchannels, qkchannels), requires_grad=True))
        self.keyMatrix = nn.Parameter(torch.empty(numheads, inchannels, qkchannels), requires_grad=True)
        self.keyNorm = nn.LayerNorm(qkchannels)
        #self.register_parameter(name='keyMatrix', param=nn.Parameter(torch.empty(numheads, inchannels, qkchannels), requires_grad=True))
        self.valueMatrix = nn.Parameter(torch.empty(numheads, inchannels, vchannels), requires_grad=True)
        #self.register_parameter(name='valueMatrix', param=nn.Parameter(torch.empty(numheads, inchannels, vchannels), requires_grad=True))
        self.valueNorm = ChannelLayerNorm(numheads*vchannels, 1, 4)

        # if given_ape == None:
        #     self.ape = gen_ape(qkchannels, self.image_size)
        # else:
        #     self.ape = given_ape # given_ape may or may not be learnable

        self.combine = nn.Conv2d(vchannels*numheads, vchannels, 1, stride=1, padding=0, bias=False)

        self.resnorm = ResidualNorm(inchannels, vchannels)

        self.mlp = MLP(vchannels, vchannels)
    
    def forward(self, x): # x should be of dimension (batch, channels, imx, imy) ->(batch, numheads, length of sequence, dimension of embedding)
        x_seq = torch.permute(torch.flatten(x, start_dim=2, end_dim=3), (0, 2, 1))
        #x_seq_pos = x_seq + self.ape
        x_seq_heads = x_seq.reshape((x_seq.shape[0],)+(1,)+x_seq.shape[1:]).repeat(1, self.numheads, 1, 1)

        x_seq_heads = self.initnorm(x_seq_heads)

        #x_seq_pos_heads = x_seq_pos.reshape((x_seq.shape[0],)+(1,)+x_seq.shape[1:]).repeat(1, self.numheads, 1, 1)
        #print("Sequence shape after head dimension ", x_seq_heads.shape)
        queries = torch.matmul(x_seq_heads, self.queryMatrix)
        keys = torch.matmul(x_seq_heads, self.keyMatrix)
        values = torch.matmul(x_seq_heads, self.valueMatrix)

        ##queries_norm = self.queryNorm(queries)
        ##keys_norm = self.keyNorm(keys)

        ##cosine_sim = torch.matmul(queries_norm, torch.permute(keys_norm, (0, 1, 3, 2))) / self.qkscalar
        cosine_sim = torch.matmul(queries, torch.permute(keys, (0, 1, 3, 2))) / self.qkscalar

        #print(torch.max(torch.abs(cosine_sim)))

        attention = F.softmax(cosine_sim, dim=3) # dimension 3 contains all dot products for one query and all keys
        tsf_out = torch.matmul(attention, values)

        # tsf_out_image will now be of shape (batch, numheads, vchannels, image_size, image_size)
        tsf_out_image = torch.unflatten(torch.permute(tsf_out, (0, 1, 3, 2)), dim=3, sizes=(self.image_size, self.image_size))
        #print("Values image shape before head stack", values_image.shape)
        
        # tsf_out_image will now be of shape (batch, numheads*vchannels, image_size, image_size)
        tsf_out_image = torch.flatten(tsf_out_image, start_dim=1, end_dim=2)
        
        tsf_out_image_norm = self.valueNorm(tsf_out_image)

        #print("Values image shape after head stack", values_image.shape)
        combined = self.combine(tsf_out_image_norm)

        out_image = self.resnorm(x, combined)

        mlp_image = self.mlp(out_image)

        return mlp_image


# --- from notebook cell 12 ---
class VisionTransformer(nn.Module):
    def __init__(self, image_size, inchannels, outchannels, numheads, numlayers):
        super(VisionTransformer, self).__init__()
        
        self.intc = [256, 4] # 512 / 8 should be a perfect square (the patch size)
        self.patch_size = 8
        self.criterion = nn.MSELoss()   # default for error(); override per call if needed

        # self.conv_layers = []
        # self.conv_layers.append(nn.Conv2d(inchannels, 32, 1, stride=1, padding=0, bias=False))
        #self.conv_layers.append(SameSizeConv(32, 32, 0, num_layers=2))

        # A registered submodule, so .to(device) reaches it and it appears in
        # state_dict() and parameters(). Its weights are frozen identity patches --
        # weights_init skips it, see the guard there.
        self.patch_conv = PatchConv(inchannels, self.patch_size) # image_size must be divisible by 8
        self.resizechannels = nn.Conv2d(inchannels*(self.patch_size**2), self.intc[0], 1, stride=1, padding=0, bias=False) # image_size must be divisible by 8
        self.norm1 = nn.BatchNorm2d(self.intc[0])

        self.transformer_layers = []
        
        self.learnable_ape = gen_learnable_ape(self.intc[0], image_size//self.patch_size)

        #self.transformer_layers.append(MultiHeadVisionAttention(image_size//self.patch_size, 4*(self.patch_size**2), 4*(self.patch_size**2), self.intc[0], numheads))
        ##self.transformer_layers.append(nn.ConvTranspose2d(self.intc[0], self.intc[1], self.patch_size, stride=self.patch_size, padding=0, bias=False) )
        ##self.transformer_layers.append(SameSizeConv(self.intc[1], self.intc[1], 0))

        for i in range(0, numlayers):
            ##self.transformer_layers.append(nn.Conv2d(self.intc[1], self.intc[0], self.patch_size, stride=self.patch_size, padding=0, bias=False))

            self.transformer_layers.append(MultiHeadVisionAttention(image_size//self.patch_size, self.intc[0], self.intc[0], self.intc[0], numheads))#, given_ape=self.learnable_ape))
            self.transformer_layers.append(nn.BatchNorm2d(self.intc[0]))
            #self.transformer_layers.append(nn.ConvTranspose2d(self.intc[0], self.intc[1], self.patch_size, stride=self.patch_size, padding=0, bias=False))
            #self.transformer_layers.append(SameSizeConv(self.intc[1], self.intc[1], 0))
        #self.transformer_layers.append( nn.ConvTranspose2d(self.intc[0], 16, 8, stride=8, padding=0, bias=False))
        self.transformer_layers.append( nn.ConvTranspose2d(self.intc[0], 64, 4, 2, 1, bias=False))
        self.transformer_layers.append(nn.BatchNorm2d(64))
        self.transformer_layers.append( nn.ConvTranspose2d(64, 16, 4, 2, 1, bias=False))
        self.transformer_layers.append(nn.BatchNorm2d(16))
        self.transformer_layers.append( nn.ConvTranspose2d(16, outchannels, 4, 2, 1, bias=False))
        self.transformer_layers.append(nn.BatchNorm2d(outchannels))

        # self.conv_layers = nn.Sequential(*self.conv_layers)
        self.transformer_layers = nn.Sequential(*self.transformer_layers)

    def forward(self, x):
        x2 = self.patch_conv(x)
        tsf_input = self.norm1(self.resizechannels(x2)) + self.learnable_ape
        return self.transformer_layers(tsf_input)

    def forward_display(self, input, tau=1.0):
        """Like forward(), but returns heatmaps ready to plot rather than to train on.

        Runs in .eval() mode under no_grad, restoring the previous mode afterwards,
        and returns (logits, probs) as lists of (B, C, H, W) tensors detached on the
        CPU. They are lists because display code loops over them without knowing how
        many outputs a given model produces; this one produces a single heatmap, so
        both lists have length 1.

        tau -- temperature applied to the logits before the softmax:
               probs = softmax(logits / tau). Below 1.0 sharpens the distribution,
               which matters when a soft-argmax reads coordinates off it: a flat
               heatmap pulls the estimate toward the image centre. 1.0 leaves the
               logits alone. The returned logits are always the raw ones.
        """
        was_training = self.training
        self.eval()
        with torch.no_grad():
            logits = self(input)
            probs = self.heatmap_softmax(logits / tau)
        if was_training:
            self.train()
        return [logits.cpu()], [probs.cpu()]

    def heatmap_softmax(self, heatmap):
        """Spatial softmax of the output logits: normalize over H*W per channel.

        Shapes are taken from the tensor, so no model_image_size global is needed and
        a batch of any size (including 1, for visualization) works unchanged.
        """
        b, c, h, w = heatmap.shape
        return F.softmax(heatmap.reshape(b, c, h * w), dim=2).reshape(b, c, h, w)

    def error(self, heatmap_logits, target, criterion=None,
              batch_size=None, loss_scale=1.0):
        """Spatial-softmax the output logits and score them against target.

        heatmap_logits -- what forward() returned.
        batch_size     -- if given, scale by (actual batch / batch_size) so a short
                          final batch contributes proportionally rather than equally.
        loss_scale     -- constant factor to lift the loss out of the range the
                          softmax leaves it in (probabilities over h*w cells are ~1e-5,
                          so MSE against them is ~1e-10 before scaling).

        Returns the loss alone. Callers that need the probabilities themselves --
        display code -- get them from forward_display().
        """
        predicted = self.heatmap_softmax(heatmap_logits)
        err = (criterion if criterion is not None else self.criterion)(predicted, target)
        if batch_size:
            err = err * predicted.shape[0] / batch_size
        return err * loss_scale


# --- from notebook cell 13 ---
def weights_init(m):
    # Leave frozen modules alone. nn.init.* writes through .data, which ignores
    # requires_grad, so without this guard model.apply(weights_init) would overwrite
    # PatchConv's fixed identity patch weights with random noise -- turning the
    # patchify operation into a random projection, silently.
    # Tested against parameters(recurse=False) because apply() visits children before
    # parents: the frozen nn.Conv2d inside PatchConv is what actually gets reached.
    own_params = list(m.parameters(recurse=False))
    if own_params and not any(p.requires_grad for p in own_params):
        return
    #print(m)
    classname = m.__class__.__name__
    if isinstance(m, nn.Linear):
        print(f"Linear {m.weight.shape}")
        nn.init.normal_(m.weight.data, 0.0, (2/(m.weight.shape[1]))**0.5)
        if hasattr(m.bias, 'data'):
            nn.init.constant_(m.bias.data, 0.0)
    elif isinstance(m, MultiHeadVisionAttention):
        print(f"MultiHeadVisionAttention {m.queryMatrix.data.shape}")
        nn.init.normal_(m.queryMatrix.data, 0.0, (2/(m.queryMatrix.data.shape[1]))**0.5)
        nn.init.normal_(m.keyMatrix.data, 0.0, (2/(m.keyMatrix.data.shape[1]))**0.5)
        nn.init.normal_(m.valueMatrix.data, 0.0, (2/(m.valueMatrix.data.shape[1]))**0.5)
    elif classname.find('BatchNorm') != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.05)
        nn.init.normal_(m.bias.data, 0.0, 0.001)
    elif isinstance(m, nn.Conv2d):
        print(f"Conv2d (2/({m.weight.shape[1]}*{m.weight.shape[2]}*{m.weight.shape[3]}))**0.5")
        nn.init.normal_(m.weight.data, 0.0, (2/(m.weight.shape[1]*m.weight.shape[2]*m.weight.shape[3]))**0.5) # shape[0] should be changed to shape[1]
        #print(m.weight.shape)
        if hasattr(m.bias, 'data'):
            nn.init.constant_(m.bias.data, 0.0)
    elif isinstance(m, nn.ConvTranspose2d):
        print(f"ConvTranspose2d (2/({m.weight.shape[0]}*(({m.weight.shape[2]}/{m.stride[0]})**2)))**0.5")
        nn.init.normal_(m.weight.data, 0.0, (2/(m.weight.shape[0]*((m.weight.shape[2]/m.stride[0])**2)))**0.5)
        #print(m.weight.shape)
        if hasattr(m.bias, 'data'):
            nn.init.constant_(m.bias.data, 0.0)
    m = m.to(torch.float32)

